modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="MIT License"

[[mods]]
# Aquí está la corrección principal
modId="essential_aspects" 
version="1.0.0" 
displayName="Essential Aspects"
logoFile="logo.png" 
authors="usearchbtw"
description='''
A Vanilla+ expansion introducing balanced combat and utility enchantments.
'''

# Cuidado aquí también, hay que quitar la variable de las dependencias
[[dependencies.essential_aspects]] 
    modId="neoforge"
    type="required" 
    versionRange="[${neo_version},)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.essential_aspects]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"